export const tablaProductos = [
    { name: "Empanadas", tipo: "empanada", costo: 150 },
    { name: "Lomo Carne", tipo: "sandwich", costo: 1000 },
    { name: "Lomo Pollo", tipo: "sandwich", costo: 900 },
    { name: "Hambur. Americana", tipo: "sandwich", costo: 900 },
    { name: "Hambur. Veggie", tipo: "sandwich", costo: 800 },
    { name: "Hambur. Clásica", tipo: "sandwich", costo: 800 },
    { name: "Sandwich Mila Carne", tipo: "sandwich", costo: 900 },
    { name: "Milanesa Carne", tipo: "sandwich", costo: 700 },
    { name: "Mila Napo Carne", tipo: "sandwich", costo: 1100 },
    { name: "Sandwich Mila Pollo", tipo: "sandwich", costo: 900 },
    { name: "Milanesa Pollo", tipo: "sandwich", costo: 700 },
    { name: "Mila Napo Pollo", tipo: "sandwich", costo: 1100 },
    { name: "Mozzarella", tipo: "pizza", costo: 1000 },
    { name: "Media Mozzarella", tipo: "pizza", costo: 600 },
    { name: "Mozzarella Doble", tipo: "pizza", costo: 1250 },
    { name: "Media Mozzarella Doble", tipo: "pizza", costo: 700 },
    { name: "Mozzarella Con Huevo", tipo: "pizza", costo: 1350 },
    { name: "Media Mozzarella Con Huevo", tipo: "pizza", costo: 750 },
    { name: "Mozzarella Super", tipo: "pizza", costo: 1350 },
    { name: "Media Mozzarella Super", tipo: "pizza", costo: 750 },
    { name: "Fugazzeta", tipo: "pizza", costo: 1350 },
    { name: "Media Fugazzeta", tipo: "pizza", costo: 750 },
    { name: "Napolitana", tipo: "pizza", costo: 1350 },
    { name: "Media Napolitana", tipo: "pizza", costo: 750 },
    { name: "Jamon Especial", tipo: "pizza", costo: 1350 },
    { name: "Media Jamon Especial", tipo: "pizza", costo: 750 },
    { name: "Roquefort", tipo: "pizza", costo: 1350 },
    { name: "Media Roquefort", tipo: "pizza", costo: 750 },
    { name: "Tres Quesos", tipo: "pizza", costo: 1350 },
    { name: "Media Tres Quesos", tipo: "pizza", costo: 750 },
    { name: "Ananá", tipo: "pizza", costo: 1450 },
    { name: "Media Ananá", tipo: "pizza", costo: 800 },
    { name: "Palmitos", tipo: "pizza", costo: 1450 },
    { name: "Media Palmitos", tipo: "pizza", costo: 800 },
    { name: "Champignon", tipo: "pizza", costo: 1450 },
    { name: "Media Champignon", tipo: "pizza", costo: 800 },
    { name: "Calabresa", tipo: "pizza", costo: 1600 },
    { name: "Media Calabresa", tipo: "pizza", costo: 850 },
    { name: "Panceta", tipo: "pizza", costo: 1600 },
    { name: "Media Panceta", tipo: "pizza", costo: 850 },
    { name: "Postres", tipo: "bebida", costo: 200 },
    { name: "Coca 500ml", tipo: "bebida", costo: 150 },
    { name: "Coca 1,5L", tipo: "bebida", costo: 320 },
    { name: "Coca  zero 1,5L", tipo: "bebida", costo: 320 },
    { name: "Sprite 1,5L", tipo: "bebida", costo: 320 },
    { name: "Sprite zero 1,5L", tipo: "bebida", costo: 320 },
    { name: "Fanta 1,5L", tipo: "bebida", costo: 320 },
    { name: "Fanta  zero 1,5L", tipo: "bebida", costo: 320 },
    { name: "Schweppes Pomelo 1,5L", tipo: "bebida", costo: 320 },
    { name: "Aquarius Pera 1,5L", tipo: "bebida", costo: 250 },
    { name: "Aquarius Manzana 1,5L", tipo: "bebida", costo: 250 },
    { name: "Aquarius Pomelo 1,5L", tipo: "bebida", costo: 250 },
    { name: "Aquarius Limonada 1,5L", tipo: "bebida", costo: 250 },
    { name: "Aquarius Citrus 1,5L", tipo: "bebida", costo: 250 },
    { name: "Pepsi 1,25L", tipo: "bebida", costo: 200 },
    { name: "Pepsi 2L", tipo: "bebida", costo: 250 },
    { name: "Pepsi 1,5L", tipo: "bebida", costo: 300 },
    { name: "Aquarius 1,5L", tipo: "bebida", costo: 280 },
    { name: "Agua Mineral 1,5L", tipo: "bebida", costo: 230 },
    { name: "Cepita 0,25L", tipo: "bebida", costo: 80 },
    { name: "Brahma 1L", tipo: "bebida", costo: 350 },
    { name: "Quilmes 1L", tipo: "bebida", costo: 350 },
    { name: "Stella 1L", tipo: "bebida", costo: 450 },
    { name: "Quilmes Stout 1L", tipo: "bebida", costo: 370 },
    { name: "Patagonia x710", tipo: "bebida", costo: 500 },
    { name: "Lata Patagonia", tipo: "bebida", costo: 300 },
    { name: "Lata Stella", tipo: "bebida", costo: 280 },
    { name: "Lata Andes", tipo: "bebida", costo: 250 },
    { name: "Lata Quilmes", tipo: "bebida", costo: 230 },
    { name: "Lata Quilmes Sin. Alc", tipo: "bebida", costo: 230 },
    { name: "Lata Quilmes N", tipo: "bebida", costo: 230 },
    { name: "Lata Wolff", tipo: "bebida", costo: 300 },
    { name: "Lata Brahma", tipo: "bebida", costo: 200 },
    { name: "Fernet Branca", tipo: "bebida", costo: 1100 },
    { name: "Vino Benjamin Malbec", tipo: "bebida", costo: 470 },
    { name: "Vino Portillo Malbec", tipo: "bebida", costo: 620 },
    { name: "Vino Portillo Pinot Noir", tipo: "bebida", costo: 620 },
    { name: "Vino Flia Gascon Syrah", tipo: "bebida", costo: 690 },
    { name: "Vino Flia Gascon Malbec", tipo: "bebida", costo: 690 },
    { name: "Vino Los Cardos ", tipo: "bebida", costo: 590 },
    { name: "Vino Vive Malbec", tipo: "bebida", costo: 630 },
    { name: "Vino Andeluna Raices", tipo: "bebida", costo: 640 },
    { name: "Vino Santa Julia Malbec Orgánico", tipo: "bebida", costo: 640 },
    { name: "Vino Cordero con Piel de Lobo", tipo: "bebida", costo: 630 },
    { name: "Vino De Moño Rojo Blanco", tipo: "bebida", costo: 630 },
    { name: "Vino De Moño Rojo Malbec", tipo: "bebida", costo: 630 },
    { name: "Vino Cafayate Malbec", tipo: "bebida", costo: 500 },
    { name: "Vino Asado Club Malbec", tipo: "bebida", costo: 590 },
    { name: "Vino Jean Rivier Malbec", tipo: "bebida", costo: 550 },
    { name: "Vino Jean Rivier Rosado", tipo: "bebida", costo: 580 },
    { name: "Vino Callia Alta Malbec ", tipo: "bebida", costo: 520 },
    { name: "Vino Domingo Hnos Otoñal", tipo: "bebida", costo: 650 },
    { name: "Vino LP Partridge Malbec", tipo: "bebida", costo: 630 },
    { name: "Vino LP Partridge Red Blend", tipo: "bebida", costo: 630 },
    { name: "Vino Laureano Gomez Rosado", tipo: "bebida", costo: 900 }
];

export const tablaPromociones = [
    { name: "Docena", descripcion: "Precio por docena", costo: 1800 },
    { name: "Promoción 1", descripcion: "2 Lomos x Pepsi 1,25", costo: 1950 },
    { name: "Promoción 2", descripcion: "2 Hamburguesas x Pepsi 1,25", costo: 2000 },
    { name: "Promoción 3", descripcion: "12 Empanadas x Pepsi 1,25", costo: 2100 },
    { name: "Promoción 4", descripcion: "6 Empanadas x Coca 0,5", costo: 2100 },

];