export const tablaProductos = [
    { name: "Empanadas", costo: 150 },
    { name: "Lomo Carne", costo: 1000 },
    { name: "Lomo Pollo", costo: 900 },
    { name: "Hambur. Americana", costo: 800 },
    { name: "Hambur. Veggie", costo: 800 },
    { name: "Hambur. Clásica", costo: 800 },
    { name: "Sandwich Milanesa", costo: 900 },
    { name: "Milanesa", costo: 700 },
    { name: "Milanesa Napolitana", costo: 1100 },
    { name: "Mozzarella", costo: 900 },
    { name: "Media Mozzarella", costo: 500 },
    { name: "Mozzarella Doble", costo: 1100 },
    { name: "Media Mozzarella Doble", costo: 600 },
    { name: "Mozzarella Con Huevo", costo: 1200 },
    { name: "Media Mozzarella Con Huevo", costo: 650 },
    { name: "Mozzarella Super", costo: 1200 },
    { name: "Media Mozzarella Super", costo: 650 },
    { name: "Fugazzeta", costo: 1200 },
    { name: "Media Fugazzeta", costo: 650 },
    { name: "Napolitana", costo: 1200 },
    { name: "Media Napolitana", costo: 650 },
    { name: "Jamon Especial", costo: 1200 },
    { name: "Media Jamon Especial", costo: 650 },
    { name: "Roquefort", costo: 1200 },
    { name: "Media Roquefort", costo: 600 },
    { name: "Tres Quesos", costo: 1200 },
    { name: "Media Tres Quesos", costo: 650 },
    { name: "Ananá", costo: 1300 },
    { name: "Media Ananá", costo: 700 },
    { name: "Palmitos", costo: 1300 },
    { name: "Media Palmitos", costo: 700 },
    { name: "Champignon", costo: 1300 },
    { name: "Media Champignon", costo: 700 },
    { name: "Calabresa", costo: 1400 },
    { name: "Media Calabresa", costo: 750 },
    { name: "Panceta", costo: 1400 },
    { name: "Media Panceta", costo: 750 },
    { name: "Postres", costo: 200 },
    { name: "Coca 500ml", costo: 150 },
    { name: "Coca 1,5L", costo: 300 },
    { name: "Pepsi 1,25L", costo: 200 },
    { name: "Pepsi 2L", costo: 250 },
    { name: "Pepsi 1,5L", costo: 300 },
    { name: "Aquarius 1,5L", costo: 250 },
    { name: "Agua Mineral 1,5L", costo: 200 },
    { name: "Cepita 0,25L", costo: 80 },
    { name: "Brahma 1L", costo: 350 },
    { name: "Quilmes 1L", costo: 350 },
    { name: "Stella 1L", costo: 450 },
    { name: "Quilmes Stout 1L", costo: 370 },
    { name: "Patagonia x710", costo: 500 },
    { name: "Lata Patagonia", costo: 300 },
    { name: "Lata Stella", costo: 250 },
    { name: "Lata Andes", costo: 220 },
    { name: "Lata Quilmes", costo: 200 },
    { name: "Lata Quilmes Sin. Alc", costo: 200 },
    { name: "Lata Quilmes N", costo: 200 },
    { name: "Lata Wolff", costo: 280 },
    { name: "Lata Brahma", costo: 200 },
    { name: "Fernet Branca", costo: 1100 },
    { name: "Vino Benjamin Malbec", costo: 470 },
    { name: "Vino Portillo Malbec", costo: 620 },
    { name: "Vino Portillo Pinot Noir", costo: 620 },
    { name: "Vino Flia Gascon Syrah", costo: 690 },
    { name: "Vino Flia Gascon Malbec", costo: 690 },
    { name: "Vino Los Cardos ", costo: 590 },
    { name: "Vino Vive Malbec", costo: 630 },
    { name: "Vino Andeluna Raices", costo: 640 },
    { name: "Vino Santa Julia Malbec Orgánico", costo: 640 },
    { name: "Vino Cordero con Piel de Lobo", costo: 630 },
    { name: "Vino De Moño Rojo Blanco", costo: 630 },
    { name: "Vino De Moño Rojo Malbec", costo: 630 },
    { name: "Vino Cafayate Malbec", costo: 500 },
    { name: "Vino Asado Club Malbec", costo: 590 },
    { name: "Vino Jean Rivier Malbec", costo: 550 },
    { name: "Vino Jean Rivier Rosado", costo: 580 },
    { name: "Vino Callia Alta Malbec ", costo: 520 },
    { name: "Vino Domingo Hnos Otoñal", costo: 650 },
    { name: "Vino LP Partridge Malbec", costo: 630 },
    { name: "Vino LP Partridge Red Blend", costo: 630 },
    { name: "Vino Laureano Gomez Rosado", costo: 900 }
]