export const tablaCalles = [
    { "label": ""},
    { "label": "1 de Mayo - VM"},
    { "label": "12 de Octubre - VM"},
    { "label": "17 de Agosto - VM"},
    { "label": "25 de Mayo - VM"},
    { "label": "9 de Julio - VM"},
    { "label": "Abelino Antuña - VM"},
    { "label": "Acapulco - VM"},
    { "label": "Aconcagua - VM"},
    { "label": "Aconquija - VM"},
    { "label": "Agustin Tosco - VM"},
    { "label": "Alaska - VM"},
    { "label": "Alberdi - VM"},
    { "label": "Alejandro D Mie - VM"},
    { "label": "Alfonsina Storni - VM"},
    { "label": "Alumine - VM"},
    { "label": "America - VM"},
    { "label": "Pasaje Andres Chazarreta - VM"},
    { "label": "Antartida Argentina - VM"},
    { "label": "Antofalla - VM"},
    { "label": "Antonio Sobral - VM"},
    { "label": "Araucanos - VM"},
    { "label": "Arenales - VM"},
    { "label": "Arequipa - VM"},
    { "label": "Boulevard Argentino - VM"},
    { "label": "Arica - VM"},
    { "label": "Arturo M Bas - VM"},
    { "label": "Asuncion - VM"},
    { "label": "Atacama - VM"},
    { "label": "Atahualpa Yupanqui - VM"},
    { "label": "Pasaje Avellaneda - VM"},
    { "label": "Ayacucho - VM"},
    { "label": "Azcuenaga - VM"},
    { "label": "B Mitre - VM"},
    { "label": "Bahia - VM"},
    { "label": "Balcarce - VM"},
    { "label": "Pasaje Bariloche - VM"},
    { "label": "Benjamin Gargiulo - VM"},
    { "label": "Beruti - VM"},
    { "label": "Bolivia - VM"},
    { "label": "Brasil - VM"},
    { "label": "Buchardo - VM"},
    { "label": "Buenos Aires - VM"},
    { "label": "C Gardel - VM"},
    { "label": "Calafate - VM"},
    { "label": "Calchaqui - VM"},
    { "label": "Cali - VM"},
    { "label": "Canada - VM"},
    { "label": "Cardiel - VM"},
    { "label": "Pasaje Carlos A Rocchi - VM"},
    { "label": "Carlos Pellegrini - VM"},
    { "label": "Cartagena - VM"},
    { "label": "Catamarca - VM"},
    { "label": "Catedral - VM"},
    { "label": "Caudillos Federales - VM"},
    { "label": "Cbo Adrian Busto - VM"},
    { "label": "Cbo N Guizzo - VM"},
    { "label": "Ceballos - VM"},
    { "label": "Avenida Centenario - VM"},
    { "label": "Cerros Colorados - VM"},
    { "label": "Cervantes - VM"},
    { "label": "Cesar A Citto - VM"},
    { "label": "Chacabuco - VM"},
    { "label": "Chaco - VM"},
    { "label": "Pasaje Champaqui - VM"},
    { "label": "Charcas - VM"},
    { "label": "Charruas - VM"},
    { "label": "Chascomus - VM"},
    { "label": "Chiclana - VM"},
    { "label": "Chile - VM"},
    { "label": "Chubut - VM"},
    { "label": "Cnel Brandsen - VM"},
    { "label": "Cnel Juan Pringles - VM"},
    { "label": "Avenida Cnel Larrabure - VM"},
    { "label": "Cnel Manuel Dorrego - VM"},
    { "label": "Colombia - VM"},
    { "label": "Congreso - VM"},
    { "label": "Constancio C Vigil - VM"},
    { "label": "Constituyentes - VM"},
    { "label": "Cordoba - VM"},
    { "label": "Corrientes - VM"},
    { "label": "Costa Rica - VM"},
    { "label": "Avenida Costanera - VM"},
    { "label": "Boulevard Cristobal Colon - VM"},
    { "label": "Curitiba - VM"},
    { "label": "Avenida Dante Alighieri - VM"},
    { "label": "Pasaje Darwin - VM"},
    { "label": "Dean Funes - VM"},
    { "label": "Avenida Del Lib G San Martin - VM"},
    { "label": "Derqui - VM"},
    { "label": "Diaguitas - VM"},
    { "label": "Domingo French - VM"},
    { "label": "Dr Amadeo Sabattini - VM"},
    { "label": "Dr Jose Aguirre Camara - VM"},
    { "label": "Dr Jose Ingenieros - VM"},
    { "label": "Dr Lisandro de la Torre - VM"},
    { "label": "Dr Luis Pasteur - VM"},
    { "label": "Dr Manuel Belgrano - VM"},
    { "label": "Dr Mariano Moreno - VM"},
    { "label": "Boulevard Dr Ramon J Carcano - VM"},
    { "label": "Dr V de la Plaza - VM"},
    { "label": "Pasaje E Massetti - VM"},
    { "label": "Ecuador - VM"},
    { "label": "El Chocon - VM"},
    { "label": "Avenida El Palmar - VM"},
    { "label": "El Rey - VM"},
    { "label": "El Salvador - VM"},
    { "label": "Elpidio Gonzalez - VM"},
    { "label": "Entre Rios - VM"},
    { "label": "Epuyen - VM"},
    { "label": "Avenida España - VM"},
    { "label": "Esquel - VM"},
    { "label": "Estados Unidos - VM"},
    { "label": "Esteban Echeverria - VM"},
    { "label": "Avenida Fagnano - VM"},
    { "label": "Pasaje Falucho - VM"},
    { "label": "Fernando Bonfiglioli - VM"},
    { "label": "Fitz Roy - VM"},
    { "label": "Florida - VM"},
    { "label": "Pasaje Formosa - VM"},
    { "label": "Francia - VM"},
    { "label": "Fray Mamerto Esquiu - VM"},
    { "label": "Gabriel Demichelis - VM"},
    { "label": "Garay - VM"},
    { "label": "Diagonal Garibaldi - VM"},
    { "label": "Gdero Baigorria - VM"},
    { "label": "Gorriti - VM"},
    { "label": "Gral Cornelio Saavedra - VM"},
    { "label": "Gral Deheza - VM"},
    { "label": "Avenida Gral Eduardo Lonardi - VM"},
    { "label": "Gral Guillermo Mosconi - VM"},
    { "label": "Gral Jose G Artigas - VM"},
    { "label": "Gral Jose Maria Paz - VM"},
    { "label": "Gral las Heras - VM"},
    { "label": "Avenida Gral Manuel N Savio - VM"},
    { "label": "Gral San Martin - VM"},
    { "label": "Gral Simon Bolivar - VM"},
    { "label": "Granaderos Argentinos - VM"},
    { "label": "Guanacache - VM"},
    { "label": "Guaranies - VM"},
    { "label": "Guatemala - VM"},
    { "label": "Guayanas - VM"},
    { "label": "Guayaquil - VM"},
    { "label": "Guillermo Rawson - VM"},
    { "label": "Haiti - VM"},
    { "label": "Hilario Ascasubi - VM"},
    { "label": "Avenida Hipolito Yrigoyen - VM"},
    { "label": "Honduras - VM"},
    { "label": "Humahuaca - VM"},
    { "label": "Ibera - VM"},
    { "label": "Iguazu - VM"},
    { "label": "Incahuasi - VM"},
    { "label": "Incas - VM"},
    { "label": "Independencia - VM"},
    { "label": "Ing Abraham Ruiz - VM"},
    { "label": "Inte Arines - VM"},
    { "label": "Inte Correa - VM"},
    { "label": "Inte de la Colina - VM"},
    { "label": "Inte Diaz - VM"},
    { "label": "Inte Maciel - VM"},
    { "label": "Inte Parajon Ortiz - VM"},
    { "label": "Inte Peña - VM"},
    { "label": "Inte Poretti - VM"},
    { "label": "Inte Reyna - VM"},
    { "label": "Inte Seydel - VM"},
    { "label": "Inte Urtubey - VM"},
    { "label": "Isaac Newton - VM"},
    { "label": "Boulevard Italia - VM"},
    { "label": "Ituzaingo - VM"},
    { "label": "J Azurduy de Padilla - VM"},
    { "label": "J M Corral - VM"},
    { "label": "Pasaje J Monti - VM"},
    { "label": "Joaquin V Gonzalez - VM"},
    { "label": "Jorge Cafrune - VM"},
    { "label": "Jorge Falcon - VM"},
    { "label": "Jorge Luis Borges - VM"},
    { "label": "Jorge Newbery - VM"},
    { "label": "Pasaje Jose Hernandez - VM"},
    { "label": "Jose Ignacio Rucci - VM"},
    { "label": "Jose Manuel Estrada - VM"},
    { "label": "Jose Maria Iturbe - VM"},
    { "label": "Jose Marti - VM"},
    { "label": "Jose Riera - VM"},
    { "label": "Jose Riesco - VM"},
    { "label": "Jose Rivera Indarte - VM"},
    { "label": "Pasaje Juan Carlos Mulinetti - VM"},
    { "label": "Juan E Muller - VM"},
    { "label": "Juan Jose Castelli - VM"},
    { "label": "Juan Manuel Fangio - VM"},
    { "label": "Jujuy - VM"},
    { "label": "Julio Cortazar - VM"},
    { "label": "Julio Sosa - VM"},
    { "label": "Junin - VM"},
    { "label": "Pasaje Juramento - VM"},
    { "label": "Avenida L N Alem - VM"},
    { "label": "La Pampa - VM"},
    { "label": "La Plata - VM"},
    { "label": "La Quiaca - VM"},
    { "label": "La Rioja - VM"},
    { "label": "Lacar - VM"},
    { "label": "Lago Argentino - VM"},
    { "label": "Lago Nahuel Huapi - VM"},
    { "label": "Laguna Blanca - VM"},
    { "label": "Lamadrid - VM"},
    { "label": "Lanin - VM"},
    { "label": "Las Bahamas - VM"},
    { "label": "Las Magnolias - VM"},
    { "label": "Las Violetas - VM"},
    { "label": "Lautaro - VM"},
    { "label": "Leopoldo Lugones - VM"},
    { "label": "Libertad - VM"},
    { "label": "Liniers - VM"},
    { "label": "Pasaje Lisignoli - VM"},
    { "label": "Lolog - VM"},
    { "label": "Los Abedules - VM"},
    { "label": "Avenida Los Alerces - VM"},
    { "label": "Los Aromos - VM"},
    { "label": "Los Ceibales - VM"},
    { "label": "Los Cipreses - VM"},
    { "label": "Los Fresnos - VM"},
    { "label": "Los Glaciares - VM"},
    { "label": "Los Lapachos - VM"},
    { "label": "Los Ombues - VM"},
    { "label": "Los Paraisos - VM"},
    { "label": "Los Pinares - VM"},
    { "label": "Los Robles - VM"},
    { "label": "Los Rosales - VM"},
    { "label": "Los Sauces - VM"},
    { "label": "Los Talas - VM"},
    { "label": "Madrid - VM"},
    { "label": "Maestros Argentinos - VM"},
    { "label": "Mafalda Gilli - VM"},
    { "label": "Magallanes - VM"},
    { "label": "Maipo - VM"},
    { "label": "Maipu - VM"},
    { "label": "Malvinas Argentinas - VM"},
    { "label": "Manuel A Ocampo - VM"},
    { "label": "Manuel Modesto Moreno - VM"},
    { "label": "Mar del Plata - VM"},
    { "label": "Maracaibo - VM"},
    { "label": "Marcelo T de Alvear - VM"},
    { "label": "Marcos Juarez - VM"},
    { "label": "Maria Curie - VM"},
    { "label": "Pasaje Maria de Luchini - VM"},
    { "label": "Mariano Pio Ceballos - VM"},
    { "label": "Martin Fierro - VM"},
    { "label": "Martinez Mendoza - VM"},
    { "label": "Matheu - VM"},
    { "label": "Diagonal Matorras de San Martin - VM"},
    { "label": "Medellin - VM"},
    { "label": "Mendoza - VM"},
    { "label": "Mercedario - VM"},
    { "label": "Mexico - VM"},
    { "label": "Miramar - VM"},
    { "label": "Miroti - VM"},
    { "label": "Misiones - VM"},
    { "label": "Monte Hermoso - VM"},
    { "label": "Monteagudo - VM"},
    { "label": "Monterrey - VM"},
    { "label": "Avenida Naciones Unidas - VM"},
    { "label": "Necochea - VM"},
    { "label": "Neuquen - VM"},
    { "label": "Nicolas Sarno - VM"},
    { "label": "Olegario V Andrade - VM"},
    { "label": "Orcadas Argentinas - VM"},
    { "label": "Orlando Biassi - VM"},
    { "label": "Pablo Colabianchi - VM"},
    { "label": "Panama - VM"},
    { "label": "Paraguay - VM"},
    { "label": "Parana - VM"},
    { "label": "Paso de la Patria - VM"},
    { "label": "Paso de los Andes - VM"},
    { "label": "Paso de los Libres - VM"},
    { "label": "Pastor C H Oviedo - VM"},
    { "label": "Patagones - VM"},
    { "label": "Paul Groussac - VM"},
    { "label": "Paysandu - VM"},
    { "label": "Pasaje Pereyra - VM"},
    { "label": "Pereyra y Arregui - VM"},
    { "label": "Periodistas Argentinos - VM"},
    { "label": "Perito F P Moreno - VM"},
    { "label": "Peru - VM"},
    { "label": "Piedras - VM"},
    { "label": "Pilcomayo - VM"},
    { "label": "Pissis - VM"},
    { "label": "Porfirio Seppey - VM"},
    { "label": "Posadas - VM"},
    { "label": "Avenida Pres Gral J A Roca - VM"},
    { "label": "Pres J Figueroa Alcorta - VM"},
    { "label": "Pres M Juarez Celman - VM"},
    { "label": "Primera Junta - VM"},
    { "label": "Progreso - VM"},
    { "label": "Providencia - VM"},
    { "label": "Provincias Unidas - VM"},
    { "label": "Avenida Pte J D Peron - VM"},
    { "label": "Puelches - VM"},
    { "label": "Puelo - VM"},
    { "label": "Puerto Montt - VM"},
    { "label": "Puerto Rico - VM"},
    { "label": "Pueyrredon - VM"},
    { "label": "Quillen - VM"},
    { "label": "Quinquela Martin N - VM"},
    { "label": "Quintana - VM"},
    { "label": "Quito - VM"},
    { "label": "R E Santoni - VM"},
    { "label": "R Saenz Peña - VM"},
    { "label": "Ramiro Suarez - VM"},
    { "label": "Pasaje Ramon Campagna - VM"},
    { "label": "Ramos Mejia - VM"},
    { "label": "Ranqueles - VM"},
    { "label": "Avenida Raul Borras - VM"},
    { "label": "Recife - VM"},
    { "label": "Reconquista - VM"},
    { "label": "Remedios de Escalada - VM"},
    { "label": "Rep de Siria - VM"},
    { "label": "Pasaje Republica - VM"},
    { "label": "Republica de Israel - VM"},
    { "label": "Republica del Libano - VM"},
    { "label": "Rio Carcaraña - VM"},
    { "label": "Rio Chubut - VM"},
    { "label": "Rio Colorado - VM"},
    { "label": "Rio Desaguadero - VM"},
    { "label": "Rio Deseado - VM"},
    { "label": "Rio Dulce - VM"},
    { "label": "Rio Limay - VM"},
    { "label": "Rio Mendoza - VM"},
    { "label": "Rio Negro - VM"},
    { "label": "Rio Parana - VM"},
    { "label": "Rio Salado - VM"},
    { "label": "Rio Sali - VM"},
    { "label": "Rio Segundo - VM"},
    { "label": "Rio Tercero - VM"},
    { "label": "Rio Tunuyan - VM"},
    { "label": "Rio Uruguay - VM"},
    { "label": "Rivadavia - VM"},
    { "label": "Ruta Nacional Rn 9 - VM"},
    { "label": "Roma - VM"},
    { "label": "Romano Ferrari - VM"},
    { "label": "Rondeau - VM"},
    { "label": "S Carbo - VM"},
    { "label": "Salomon Deiver - VM"},
    { "label": "Avenida Salomon Gornitz - VM"},
    { "label": "Salta - VM"},
    { "label": "Salto Grande - VM"},
    { "label": "San Juan - VM"},
    { "label": "San Lorenzo - VM"},
    { "label": "San Luis - VM"},
    { "label": "San Roque - VM"},
    { "label": "Santa Cruz - VM"},
    { "label": "Santa Fe - VM"},
    { "label": "Pasaje Santa Lucia - VM"},
    { "label": "Santa Marta - VM"},
    { "label": "Santiago Balerdi - VM"},
    { "label": "Santiago del Estero - VM"},
    { "label": "Boulevard Sarmiento - VM"},
    { "label": "Sarratea - VM"},
    { "label": "Sgto Juan B Cabral - VM"},
    { "label": "Soler - VM"},
    { "label": "Solis - VM"},
    { "label": "Sucre - VM"},
    { "label": "Suiza - VM"},
    { "label": "Tacuari - VM"},
    { "label": "Tehuelches - VM"},
    { "label": "Teniente 1Ro Ibañez - VM"},
    { "label": "Thomas Edison - VM"},
    { "label": "Tierra del Fuego - VM"},
    { "label": "Tobas - VM"},
    { "label": "Tomas Espora - VM"},
    { "label": "Traful - VM"},
    { "label": "Tromen - VM"},
    { "label": "Tronador - VM"},
    { "label": "Tucuman - VM"},
    { "label": "Tupungato - VM"},
    { "label": "Avenida Universidad - VM"},
    { "label": "Uruguay - VM"},
    { "label": "Ushuaia - VM"},
    { "label": "Uspallata - VM"},
    { "label": "Valparaiso - VM"},
    { "label": "Boulevard Velez Sarsfield - VM"},
    { "label": "Venezuela - VM"},
    { "label": "Veracruz - VM"},
    { "label": "Viamonte - VM"},
    { "label": "Vicente Lopez y Planes - VM"},
    { "label": "Victor Mercante - VM"},
    { "label": "Victoria Ocampo - VM"},
    { "label": "Viedma - VM"},
    { "label": "Viena - VM"},
    { "label": "Viña del Mar - VM"},
    { "label": "Walt Disney - VM"},
    { "label": "Pasaje Yapeyu - VM"},
    { "label": "1 de Mayo - VN"},
    { "label": "12 de Octubre - VN"},
    { "label": "2 de Abril - VN"},
    { "label": "25 de Mayo - VN"},
    { "label": "4 de Septiembre - VN"},
    { "label": "5 de Julio - VN"},
    { "label": "9 de Julio - VN"},
    { "label": "Alberdi - VN"},
    { "label": "Alte G Brown - VN"},
    { "label": "Ambrosio Olmos - VN"},
    { "label": "Antartida Argentina - VN"},
    { "label": "Antonio Rivero - VN"},
    { "label": "Boulevard Argentino - VN"},
    { "label": "B Mitre - VN"},
    { "label": "Bernardino Rivadavia - VN"},
    { "label": "Buenos Aires - VN"},
    { "label": "Calle 1 - VN"},
    { "label": "Calle 2 - VN"},
    { "label": "Camarero Gonzalez - VN"},
    { "label": "Carlos Alberto Moreno - VN"},
    { "label": "Avenida Carranza - VN"},
    { "label": "Catamarca - VN"},
    { "label": "Ceferino Namuncura - VN"},
    { "label": "Cervantes - VN"},
    { "label": "Chacabuco - VN"},
    { "label": "Chaco - VN"},
    { "label": "Chubut - VN"},
    { "label": "Comercio - VN"},
    { "label": "Cordoba - VN"},
    { "label": "Pasaje Coria - VN"},
    { "label": "Corrientes - VN"},
    { "label": "Avenida Costanera - VN"},
    { "label": "Cristobal Colon - VN"},
    { "label": "Dean Funes - VN"},
    { "label": "Domingo F Sarmiento - VN"},
    { "label": "Dr Jose Ingenieros - VN"},
    { "label": "Dr Lisandro de la Torre - VN"},
    { "label": "Dr Manuel Belgrano - VN"},
    { "label": "Dr Nicolas Avellaneda - VN"},
    { "label": "Dr Ramon J Carcano - VN"},
    { "label": "Pasaje Dr Ramon J Carcano - VN"},
    { "label": "Dr Velez Sarsfield - VN"},
    { "label": "El Aguaribay - VN"},
    { "label": "El Jacaranda - VN"},
    { "label": "Entre Rios - VN"},
    { "label": "España - VN"},
    { "label": "Eva Peron - VN"},
    { "label": "Florida - VN"},
    { "label": "Formosa - VN"},
    { "label": "Francisco de Laprida - VN"},
    { "label": "Garcia Lorca - VN"},
    { "label": "Gdor Luis Vernet - VN"},
    { "label": "Gral Cornelio Saavedra - VN"},
    { "label": "Cortada Gral Guemes - VN"},
    { "label": "Gral J J de Urquiza - VN"},
    { "label": "Gral Jose Maria Paz - VN"},
    { "label": "Gral San Martin - VN"},
    { "label": "Gral Simon Bolivar - VN"},
    { "label": "Pasaje Gran Chaparral - VN"},
    { "label": "Hilario Ascasubi - VN"},
    { "label": "Avenida Humberto Barberis - VN"},
    { "label": "Independencia - VN"},
    { "label": "Inte Pavioti - VN"},
    { "label": "Isabel la Catolica - VN"},
    { "label": "Islas Malvinas - VN"},
    { "label": "Italia - VN"},
    { "label": "Ituzaingo - VN"},
    { "label": "Jujuy - VN"},
    { "label": "L N Alem - VN"},
    { "label": "La Pampa - VN"},
    { "label": "Las Acacias - VN"},
    { "label": "Las Palmeras - VN"},
    { "label": "Libertad - VN"},
    { "label": "Lima - VN"},
    { "label": "Los Abedules - VN"},
    { "label": "Los Alamos - VN"},
    { "label": "Los Alerces - VN"},
    { "label": "Los Algarrobos - VN"},
    { "label": "Avenida Los Arrayanes - VN"},
    { "label": "Los Caldenes - VN"},
    { "label": "Los Cedros - VN"},
    { "label": "Avenida Los Ceibos - VN"},
    { "label": "Los Chañares - VN"},
    { "label": "Avenida Los Eucaliptus - VN"},
    { "label": "Los Fresnos - VN"},
    { "label": "Los Lapachos - VN"},
    { "label": "Los Nogales - VN"},
    { "label": "Los Olivares - VN"},
    { "label": "Los Paraisos - VN"},
    { "label": "Los Pinos - VN"},
    { "label": "Los Platanos - VN"},
    { "label": "Los Quebrachos - VN"},
    { "label": "Los Robles - VN"},
    { "label": "Los Sauces - VN"},
    { "label": "Los Tilos - VN"},
    { "label": "Madre Transito Cabanillas - VN"},
    { "label": "Maipu - VN"},
    { "label": "Mansilla - VN"},
    { "label": "Manuel de Falla - VN"},
    { "label": "Manuel Modesto Moreno - VN"},
    { "label": "Marcos Juarez - VN"},
    { "label": "Misiones - VN"},
    { "label": "Monte Hermoso - VN"},
    { "label": "Necochea - VN"},
    { "label": "Neuquen - VN"},
    { "label": "Paraguay - VN"},
    { "label": "Avenida Patria - VN"},
    { "label": "Pedro de Mendoza - VN"},
    { "label": "Piedras - VN"},
    { "label": "Pinamar - VN"},
    { "label": "Pres Gral J A Roca - VN"},
    { "label": "Pres M Juarez Celman - VN"},
    { "label": "Pres Santiago Derqui - VN"},
    { "label": "Pte H Yrigoyen - VN"},
    { "label": "Pte M T de Alvear - VN"},
    { "label": "Puerto Argentino - VN"},
    { "label": "R Saenz Peña - VN"},
    { "label": "Rio Negro - VN"},
    { "label": "Rioja - VN"},
    { "label": "Ruta Provincial Rp 2 - VN"},
    { "label": "Salta - VN"},
    { "label": "San Juan - VN"},
    { "label": "San Lorenzo - VN"},
    { "label": "San Luis - VN"},
    { "label": "Santa Fe - VN"},
    { "label": "Santiago del Estero - VN"},
    { "label": "Sgto Juan B Cabral - VN"},
    { "label": "Spinelli Elvio - VN"},
    { "label": "Tierra del Fuego - VN"},
    { "label": "Tucuman - VN"},
    { "label": "Vicente Lopez y Planes - VN"},
    { "label": "Villa Gesell - VN"}
]
